version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://admin:password@mongo:27017/auth_db?authSource=admin
      - JWT_SECRET=rahasia
      - PORT=3000
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3001:3001"
    environment:
      - DB_URL=mongodb://admin:password@mongo:27017/product_db?authSource=admin
      - PORT=3001
    depends_on:
      - mongo

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "3002:3002"
    environment:
      - DB_URL=mongodb://admin:password@mongo:27017/cart_db?authSource=admin
      - PORT=3002
    depends_on:
      - mongo
